services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build: ./Producer/
    depends_on:
      - rabbitmq
    environment:
      RabbitMQ__Host: rabbitmq

  consumer:
    build: ./Consumer
    depends_on:
      - rabbitmq
    environment:
      RabbitMQ__Host: rabbitmq
